version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
    postgres:
        image: postgres:9.6
        env_file:
            - .env
    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
            - redis
        env_file:
            - .env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./data:/usr/local/airflow/data
            - shared_logs:/usr/local/airflow/logs
            - ./logs:/usr/local/airflow/logs
        ports:
            - "8080:8080"
        command: webserver
    flower:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - redis
        env_file:
            - .env
        ports:
            - "5555:5555"
        command: flower
    scheduler:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./data:/usr/local/airflow/data
            - shared_logs:/usr/local/airflow/logs
            - ./logs:/usr/local/airflow/logs
        env_file:
            - .env
        command: scheduler
    worker:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./data:/usr/local/airflow/data
            - shared_logs:/usr/local/airflow/logs
            - ./logs:/usr/local/airflow/logs
        env_file:
            - .env
        command: worker

volumes:
  shared_logs: